name: Keep Backend Alive

on:
  schedule:
    - cron: "*/10 * * * *" # every 10 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Express backend
        run: |
          curl -X GET http://localhost/5000/health
